# Rename to application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 'xxxxxx'
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Blog数据源配置
    blog:
      url: jdbc:mysql://localhost:3306/shana?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 'xxxxxx'
      driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发环境打印 SQL 日志
